### ISSUE TITLE
Implementation method

### ISSUE THREAD

**Issue by farajist** [Salama-has/classes.prj1#1]
The script uses built-in module `ipadress` which hides implementation details, you should:
* Implement the logic from scratch (string parsing, class identification)
* Check the documentation of the module and try to implement other interesting ideas [ipadress py docs](https://docs.python.org/3/library/ipaddress.html)

**Comment by Salama-has** [comment]
> The script uses built-in module `ipadress` which hides implementation details, you should:
> 
> * Implement the logic from scratch (string parsing, class identification)
> * Check the documentation of the module and try to implement other interesting ideas [ipadress py docs](https://docs.python.org/3/library/ipaddress.html)
